In [7]:
import numpy as np

def huruf2array(huruf):
    huruf=huruf.replace("#","1,")
    huruf=huruf.replace(".","-1,")
    huruf=huruf.replace("\n",'')
    arr = np.fromstring(huruf[:-1],dtype=int,sep=',')
    return arr

'''Test method huruf2array'''
#file = open("data/huruf_a.txt", 'r')
#x = file.read()
#file.close()

#print(huruf2array(x))

'Test method huruf2array'

In [24]:
class SLP(object):
    def __init__(self,size,np_size):
        self.weight = np.zeros((size,np_size))
        self.bias = np.zeros(size)

    def train(self,train_data,train_target,threshold):
        epoch = 1
        stop = False
        while stop is False:
            print("epoch ", epoch)
            stop = True
            for i in range(len(train_data)): # 2
                v = np.zeros(len(train_target))
                y = np.zeros(len(train_target))
                for j in range(len(train_target)): # 2
                    v[j] = np.dot(train_data[i], self.weight[j]) + self.bias[j]
                    y[j] = self.fungsi_aktivasi(v[j], threshold)
                    if y[j] != train_target[i][j]:
                        stop = False
                        self.weight[j] = self.weight[j] + (train_target[i][j] * train_data[i])
                        self.bias[j] = self.bias[j] + train_target[i][j]
            epoch = epoch + 1
            print("stop", stop)

    def test(self, test_data, threshold):
        v = np.zeros(len(self.weight))
        y = np.zeros(len(self.weight))
        for i in range(len(self.weight)):
            v[i] = np.dot(test_data, self.weight[i]) + self.bias[i]
            y[i] = self.fungsi_aktivasi(v[i], threshold)
        return y

    def fungsi_aktivasi(self, v, threshold):
        if v > threshold:
            return 1
        elif threshold >= v and v >= -(threshold):
            return 0
        else:
            return -1

    def get_weight(self):
        return (self.weight,self.bias)

In [25]:
#Data Target
huruf_a = [ 1 if i == 0 else -1 for i in range(7) ]
huruf_b = [ 1 if i == 1 else -1 for i in range(7) ]
huruf_c = [ 1 if i == 2 else -1 for i in range(7) ]
huruf_d = [ 1 if i == 3 else -1 for i in range(7) ]
huruf_e = [ 1 if i == 4 else -1 for i in range(7) ]
huruf_j = [ 1 if i == 5 else -1 for i in range(7) ]
huruf_k = [ 1 if i == 6 else -1 for i in range(7) ]

# dataTrain = huruf_a + huruf_b + huruf_c + huruf_d + huruf_e + huruf_j + huruf_k
dataTrain = [huruf_a, huruf_b, huruf_c, huruf_d, huruf_e, huruf_j, huruf_k]

np_dataTrain=np.array(dataTrain)
print(np_dataTrain)
#dibikin perindexdari tiap huruf
#print(huruf_a)
#print(huruf_b)

[[ 1 -1 -1 -1 -1 -1 -1]
 [-1  1 -1 -1 -1 -1 -1]
 [-1 -1  1 -1 -1 -1 -1]
 [-1 -1 -1  1 -1 -1 -1]
 [-1 -1 -1 -1  1 -1 -1]
 [-1 -1 -1 -1 -1  1 -1]
 [-1 -1 -1 -1 -1 -1  1]]


In [26]:
# Read all data
file = open("data/list_data_latih.txt", 'r')
listDataLatih = file.read()
file.close()

listDataLatih = listDataLatih.replace("\n", ",")
arrDataLatih = listDataLatih.split(',')

# create data latih in numpy array
dataLatih = []
for namafile in arrDataLatih:
    file = open("data/" + namafile, 'r')
    huruf = file.read()
    dataLatih.append(huruf2array(huruf))
    
dataLatih = np.array(dataLatih)
print((dataLatih))

[[-1 -1  1  1 -1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1  1
  -1  1 -1 -1 -1 -1  1 -1  1 -1 -1 -1  1  1  1  1  1 -1 -1  1 -1 -1 -1  1
  -1 -1  1 -1 -1 -1  1 -1  1  1  1 -1  1  1  1]
 [ 1  1  1  1  1  1 -1 -1  1 -1 -1 -1 -1  1 -1  1 -1 -1 -1 -1  1 -1  1 -1
  -1 -1 -1  1 -1  1  1  1  1  1 -1 -1  1 -1 -1 -1 -1  1 -1  1 -1 -1 -1 -1
   1 -1  1 -1 -1 -1 -1  1  1  1  1  1  1  1 -1]
 [-1 -1  1  1  1  1  1 -1  1 -1 -1 -1 -1  1  1 -1 -1 -1 -1 -1 -1  1 -1 -1
  -1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1
  -1 -1  1 -1 -1 -1 -1  1 -1 -1  1  1  1  1 -1]
 [ 1  1  1  1  1 -1 -1 -1  1 -1 -1 -1  1 -1 -1  1 -1 -1 -1 -1  1 -1  1 -1
  -1 -1 -1  1 -1  1 -1 -1 -1 -1  1 -1  1 -1 -1 -1 -1  1 -1  1 -1 -1 -1 -1
   1 -1  1 -1 -1 -1  1 -1  1  1  1  1  1 -1 -1]
 [ 1  1  1  1  1  1  1 -1  1 -1 -1 -1 -1  1 -1  1 -1 -1 -1 -1 -1 -1  1 -1
   1 -1 -1 -1 -1  1  1  1 -1 -1 -1 -1  1 -1  1 -1 -1 -1 -1  1 -1 -1 -1 -1
  -1 -1  1 -1 -1 -1 -1  1  1  1  1  1  1  1  1]
 [-1 -1 -1  1  1  1 

In [27]:
#training data

data = dataLatih
target = np.array(dataTrain)
threshold = 0.2
print(target)
slp = SLP(7,63)
slp.train(data,target,threshold)

(bobot,bias)=slp.get_weight()
print("bobot")
print(bobot)
print("bias")
print(bias)

[[ 1 -1 -1 -1 -1 -1 -1]
 [-1  1 -1 -1 -1 -1 -1]
 [-1 -1  1 -1 -1 -1 -1]
 [-1 -1 -1  1 -1 -1 -1]
 [-1 -1 -1 -1  1 -1 -1]
 [-1 -1 -1 -1 -1  1 -1]
 [-1 -1 -1 -1 -1 -1  1]]
epoch  1
stop False
epoch  2
stop False
epoch  3
stop False
epoch  4
stop True
bobot
[[-1. -1.  1. -1. -3. -3. -1.  1. -1.  1.  3.  1. -1. -1.  1. -1.  1.  3.
   1. -1. -1.  1. -1.  3.  1.  3. -1. -1.  1. -1.  1. -1.  1. -3.  1.  1.
   1.  3.  3.  3.  1. -1.  1. -1.  1.  1.  1.  1. -1.  1. -1.  1.  1.  1.
   1. -1.  1.  1. -1. -3. -1.  1.  3.]
 [ 2.  2. -2. -2.  0.  2. -2.  2.  0.  2.  0.  2.  0.  2.  0.  2.  2.  0.
   2.  2.  4.  0.  2.  0.  0.  0.  2.  4.  0.  2.  2.  4.  4.  6.  0.  0.
   0.  0. -2.  0.  0.  4.  0.  0.  2.  2.  2.  0.  4.  2. -2.  2.  2.  2.
  -2.  2.  0.  0. -2.  0. -2.  0. -2.]
 [-1. -1. -1. -1.  1.  3.  3.  1.  1.  1. -1.  1. -1.  3.  3. -1.  1. -1.
   1.  1. -1.  3. -1. -1.  1. -1.  1. -1.  3. -1. -1.  1. -1.  1. -1.  3.
  -3. -1. -1. -1. -1. -1.  3. -3.  1.  1.  1. -1. -1.  1. -1.  1.  1.  1.
  

In [28]:
def cekHuruf(hasil):
    if np.array_equal(hasil, np_dataTrain[0]):
        return "a"
    elif np.array_equal(hasil, np_dataTrain[1]):
        return "b"
    elif np.array_equal(hasil, np_dataTrain[2]):
        return "c"
    elif np.array_equal(hasil, np_dataTrain[3]):
        return "d"
    elif np.array_equal(hasil, np_dataTrain[4]):
        return "e"
    elif np.array_equal(hasil, np_dataTrain[5]):
        return "j"
    elif np.array_equal(hasil, np_dataTrain[6]):
        return "k"

In [45]:
#data uji
file = open("data/list_data_uji.txt", 'r')
dataset_uji = file.read()
file.close()

dataset_uji = dataset_uji.replace("\n", ",")
arrDataUji = dataset_uji.split(',')

# create data latih in numpy array
dataUji = []
for namafile in arrDataUji:
    file = open("data/" + namafile, 'r')
    huruf = file.read()
    dataUji.append(huruf2array(huruf))
    
dataUji = np.array(dataUji)

for index, data_uji in enumerate(dataUji):
    print("data uji", index, end=" : ")
    hasil_uji = slp.test(data_uji, threshold)
    print(cekHuruf(hasil_uji))

data uji 0 : None
data uji 1 : None
data uji 2 : None
data uji 3 : d
data uji 4 : c
data uji 5 : c
data uji 6 : k
