In [39]:
import numpy as np

def huruf2array(huruf):
    huruf=huruf.replace("#","1,")
    huruf=huruf.replace(".","-1,")
    huruf=huruf.replace("\n",'')
    arr = np.fromstring(huruf[:-1],dtype=int,sep=',')
    return arr

'''Test method huruf2array'''
file = open("data/huruf_a.txt", 'r')
x = file.read()
file.close()

print(huruf2array(x))

[-1 -1 -1  1 -1 -1 -1 -1 -1  1  1  1 -1 -1 -1  1  1 -1  1  1 -1  1  1 -1
 -1 -1  1  1  1  1  1  1  1  1  1  1 -1 -1 -1 -1 -1  1  1 -1 -1 -1 -1 -1
  1]


In [227]:
class SLP(object):
    def __init__(self,size,np_size):
        self.weight = np.zeros((size,np_size))
        self.bias = np.zeros(size)

    def train(self,train_data,train_target,threshold):
        stop = False
        while stop is False:
            stop = True
            v = np.zeros(len(train_target))
            y = np.zeros(len(train_target))
            for i in range(len(train_data[0])):
                for j in range(len(train_target)):
                    v[j] = np.dot(train_data[j],self.weight[j])+ self.bias[j]
                    y[j] = self.aktivasi(v[j],threshold)
                    if y[j] != train_target[i][j]:
                        stop = False
                        self.weight[i][j] = self.weight[i][j] + train_target[j] * train_data[j][i]
                        self.bias[j] = self.bias[j] + train_target[j]
    #             for i in range(len(train_data)):
#                 for j in range(len(train_target)):
#                     v= train_data[i] * self.weight[i][j]+ self.bias
# #                     v = np.dot()
#                     y= self.aktivasi(v,threshold)
#                     if y[j] != train_target[i][j]:
#                         stop = False
#                         self.weight = self.weight + alpha * train_target[i][j] * train_data
#                         self.bias = self.bias + alpha * train_target[i][j]

    def test(self,weight,bias,test_data,threshold):
        v = np.dot(test_data,self.weight)+ self.bias
        y = self.aktivasi(v,threshold)
        return y

    def aktivasi(self,x,threshold):
        if x>threshold:
            return 1
        if x < -threshold:
            return -1
        else:
            return 0

    def get_weight(self):
        return (self.weight,self.bias)

In [217]:
'''class SLP():
   def __init__(self, size):
        self.weight = np.zeros(size)
        self.bias = 0
    
    def fungsi_aktivasi(self, v, threshold):
        if v > threshold:
            return 1
        elif threshold >= v and v >= -(threshold):
            return 0
        else:
            return -1
'''

'class SLP():\n   def __init__(self, size):\n        self.weight = np.zeros(size)\n        self.bias = 0\n    \n    def fungsi_aktivasi(self, v, threshold):\n        if v > threshold:\n            return 1\n        elif threshold >= v and v >= -(threshold):\n            return 0\n        else:\n            return -1\n'

In [202]:
#Data Target
huruf_a = [ 1 if i == 0 else -1 for i in range(7) ]
huruf_b = [ 1 if i == 1 else -1 for i in range(7) ]
huruf_c = [ 1 if i == 2 else -1 for i in range(7) ]
huruf_d = [ 1 if i == 3 else -1 for i in range(7) ]
huruf_e = [ 1 if i == 4 else -1 for i in range(7) ]
huruf_j = [ 1 if i == 5 else -1 for i in range(7) ]
huruf_k = [ 1 if i == 6 else -1 for i in range(7) ]

# dataTrain = huruf_a + huruf_b + huruf_c + huruf_d + huruf_e + huruf_j + huruf_k
dataTrain = [huruf_a, huruf_b, huruf_c, huruf_d, huruf_e, huruf_j, huruf_k]

np_dataTrain=np.array(dataTrain)
print(np_dataTrain)
#dibikin perindexdari tiap huruf
#print(huruf_a)
#print(huruf_b)

[[ 1 -1 -1 -1 -1 -1 -1]
 [-1  1 -1 -1 -1 -1 -1]
 [-1 -1  1 -1 -1 -1 -1]
 [-1 -1 -1  1 -1 -1 -1]
 [-1 -1 -1 -1  1 -1 -1]
 [-1 -1 -1 -1 -1  1 -1]
 [-1 -1 -1 -1 -1 -1  1]]


In [203]:
# Read all data
file = open("data/list_data_latih.txt", 'r')
listDataLatih = file.read()
file.close()

listDataLatih = listDataLatih.replace("\n", ",")
arrDataLatih = listDataLatih.split(',')

# create data latih in numpy array
dataLatih = []
for namafile in arrDataLatih:
    file = open("data/" + namafile, 'r')
    huruf = file.read()
    dataLatih.append(huruf2array(huruf))
    
dataLatih = np.array(dataLatih)
print((dataLatih))

[[-1 -1 -1  1 -1 -1 -1 -1 -1  1  1  1 -1 -1 -1  1  1 -1  1  1 -1  1  1 -1
  -1 -1  1  1  1  1  1  1  1  1  1  1 -1 -1 -1 -1 -1  1  1 -1 -1 -1 -1 -1
   1]
 [ 1  1  1  1  1  1 -1  1 -1 -1 -1 -1 -1  1  1 -1 -1 -1 -1 -1  1  1  1  1
   1  1  1 -1  1 -1 -1 -1 -1 -1  1  1 -1 -1 -1 -1 -1  1  1  1  1  1  1  1
  -1]
 [-1  1  1  1  1  1  1  1 -1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1  1 -1 -1
  -1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1 -1  1  1  1  1  1
   1]
 [ 1  1  1  1  1  1 -1  1 -1 -1 -1 -1 -1  1  1 -1 -1 -1 -1 -1  1  1 -1 -1
  -1 -1 -1  1  1 -1 -1 -1 -1 -1  1  1 -1 -1 -1 -1 -1  1  1  1  1  1  1  1
  -1]
 [ 1  1  1  1  1  1  1  1 -1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1  1  1  1
   1  1  1 -1  1 -1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1  1  1  1  1  1  1
   1]
 [ 1  1  1  1  1  1  1 -1 -1 -1  1  1 -1 -1 -1 -1 -1  1  1 -1 -1 -1 -1 -1
   1  1 -1 -1 -1 -1 -1  1  1 -1 -1  1 -1 -1  1  1 -1 -1 -1  1  1  1 -1 -1
  -1]
 [ 1 -1 -1 -1 -1 -1  1  1 -1 -1 -1 -1  1 -1  1 -1 -1 -1  1 -1 -1  1  1  1
  

In [228]:
#training data

data = dataLatih
target = np.array(dataTrain)
threshold = 0.2
print(target)
slp = SLP(7,49)
slp.train(data,target,threshold)

(bobot,bias)=slp.get_weight()
print(bobot)
print(bias)

[[ 1 -1 -1 -1 -1 -1 -1]
 [-1  1 -1 -1 -1 -1 -1]
 [-1 -1  1 -1 -1 -1 -1]
 [-1 -1 -1  1 -1 -1 -1]
 [-1 -1 -1 -1  1 -1 -1]
 [-1 -1 -1 -1 -1  1 -1]
 [-1 -1 -1 -1 -1 -1  1]]


ValueError: setting an array element with a sequence.

In [178]:
for data_uji in data:
    hasil_uji = slp.test(bobot,bias,data_uji,threshold)
    print(hasil_uji)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()